### ISSUE TITLE
Fetch NetworkManagement resources

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-gcp#1]
Hello, do you plan on ingesting https://pkg.go.dev/google.golang.org/api@v0.39.0/networkmanagement/v1#LoadBalancerInfo and https://pkg.go.dev/google.golang.org/api@v0.39.0/networkmanagement/v1#LoadBalancerBackend?

Thanks for the good work :)

**Comment by xino12** [comment]
Well I see there's no way to list those resources as I'm digging in  google API doc. Maybe I'm trying to list https://cloud.google.com/compute/docs/reference/rest/v1/backendServices/list instead

**Comment by yevgenypats** [comment]
@xino12 Thanks for posting this issue! I'll take a look at that.

**Comment by yevgenypats** [comment]
@xino12 I've added `compute.backend_services` in [v0.0.5](https://github.com/cloudquery/cq-provider-gcp/releases/tag/v0.0.5). Can you please test and let me know if that answers your use-case or do we need to ingest other data for your use-case?

**Comment by xino12** [comment]
Thanks @yevgenypats. 

It helps my use-case :)
