### ISSUE TITLE
Look into switching client into https://github.com/googleapis/google-cloud-go

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cq-provider-gcp#106]
Currently https://github.com/googleapis/google-api-go-client#status is in maintains mode. It might be beneficial to switch to Look into switching client into https://github.com/googleapis/google-cloud-go.

For example some things are better in the new one and might have more support for more services. 

https://github.com/googleapis/google-api-go-client/issues/142
https://github.com/cloudquery/cq-provider-gcp/blob/main/client/retry.go

**Comment by roneli** [comment]
Closing as the google-cloud-go uses the underlying API so it doesn't really matter.
