### ISSUE TITLE
Support Folder in addition to Project

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-gcp#184]
Right now when CQ grabs assets it does so by iterating through a list of projects that is defined in the `config.hcl`. As customers grow their infrastructure they organize their projects into hierarchical structures where folders contain projects and other folders.

A customer should be able to give us a list of folder ids and CloudQuery should recursively find all projects in that folder.

**Comment by TinLe** [comment]
Thank you for creating this ticket.  An additional nice-to-have is the ability to specify depth of scan for folder(s).  E.g. folders can nest, so ability specify how many levels to scan is very useful.

**Comment by bbernays** [comment]
Implemented in #188
