### ISSUE TITLE
No useful error shows up for the user if they are not authenticated with GCP

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cq-provider-gcp#213]
### Describe the bug

Running `cloudquery fetch` without GCP credentials doesn't show up useful "authentication failed" info to the user:
```
~/projects/cqgcp % cloudquery fetch
Initializing CloudQuery Providers...

✓ cq-provider-gcp@v0.7.0 verified    1s  100 %

Finished provider initialization...

Upgrading CloudQuery providers gcp

✓ Upgraded provider gcp to latest successfully.

Finished upgrading providers...

Starting provider fetch...

⌛cq-provider-gcp@latest fetching    0s [--------------------------------------------------------------|  Finished Resources: 0/36
⌛cq-provider-gcp@latest fetching    0s [--------------------------------------------------------------|  Finished Resources: 0/36
```

Should also review the errors the other providers return in this case.

### Expected Behavior

Error should be more useful

### Steps to Reproduce

```
cloudquery init gcp
cloudquery fetch
```

### Provider and CloudQuery version

Version: 0.22.10 Commit: b953309e81b8d16cb2afa0cefb9c91f6dd74554d Date: 2022-04-27T10:18:37Z

### Additional Context

GCP provider version  = `0.7.0`

**Comment by erezrokah** [comment]
Hi @shimonp21, thank you for opening the issue 🚀  Is https://github.com/cloudquery/cq-provider-gcp/issues/212 a duplicate of this issue?

**Comment by shimonp21** [comment]
Fixed in latest version :) 

![image](https://user-images.githubusercontent.com/37939765/168569804-b7aae24e-427e-4ec4-838d-c5d6a76d5ffd.png)
