### ISSUE TITLE
Some GCP resources that are missing

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-gcp#3]
Hello, could we add these GCP resources?

Compute API
-------------------
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#Network
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#SubNetwork
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#NetworkEndpoint
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#Firewall
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#FirewallAllowed
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#FirewallDenied
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#FirewallPolicy
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#FirewallPolicyAssociation
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#ProjectsGetXpnResources
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#SecurityPolicy
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#SecurityPolicyRule
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#SslCertificate

Container API
---------------------
https://pkg.go.dev/google.golang.org/api@v0.39.0/container/v1#Cluster

Thanks for the good work :)

**Comment by yevgenypats** [comment]
I've added `networks,firewalls,subnetworks` in [v0.0.7](https://github.com/cloudquery/cq-provider-gcp/releases/tag/v0.0.7). I'll added the other resources later today.

**Comment by xino12** [comment]
🏆 thank you so much
