### ISSUE TITLE
Add GCP project resource

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-gcp#4]
Could we add as well
https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#Project please?

Thanks :)

**Comment by bwalding** [comment]
You told me you were doing all this work yourself!

**Comment by yevgenypats** [comment]
I used this [API](https://pkg.go.dev/google.golang.org/api@v0.40.0/cloudresourcemanager/v1#Project) it also exposes labels. Released in [v0.0.8](https://github.com/cloudquery/cq-provider-gcp/releases/tag/v0.0.8)
