### ISSUE TITLE
Support for Network Load Balancers

### ISSUE THREAD

**Issue by jbertman** [cloudquery/cq-provider-gcp#47]
Looking to see if CQ can support Load Balancers to help enumerate public facing infrastructure: 
https://cloud.google.com/load-balancing
https://console.cloud.google.com/net-services/loadbalancing/list

Let me know what you think!

**Comment by roneli** [comment]
I don't think a specific API exists for this in the gcp SDK, as apparently its part of the compute service. 

https://github.com/googleapis/google-api-go-client/issues/240

We can add URLMaps API
https://cloud.google.com/sdk/gcloud/reference/compute/url-maps/list

**Comment by jbertman** [comment]
Ah good callout, I think that combined with the existing forwarding rules table should cover the use case 🚀
